package oj.test;

import java.util.HashMap;
import java.util.Map;

/**
 * Given two strings s and t which consist of only lowercase letters.<br/>
 * String t is generated by random shuffling string s and then add one more letter at a random position.
 * Find the letter that was added in t.
 */
public class FindTheDifference {

    public static char findTheDifference(String s, String t) {
//        Map<Character, Integer> map = new HashMap<Character, Integer>();
//        char[] sChars = s.toCharArray();
//        char[] tChars = t.toCharArray();

//        for (int i = 0; i < s.length(); i++) {
//            char ch = s.charAt(i);
//            if (map.containsKey(ch)) {
//                map.put(ch, map.get(ch) + 1);
//            } else {
//                map.put(ch, 1);
//            }
//        }
//
//        for (int i = 0; i < t.length(); i++) {
//            char ch = t.charAt(i);
//            if (map.containsKey(ch)) {
//                map.put(ch, map.get(ch) - 1);
//                if (0 == map.get(ch)) {
//                    map.remove(ch);
//                }
//            } else {
//                return ch;
//            }
//        }

//        return map.keySet().iterator().next();

        //使用异或操作可以把不同的位找出来
        char re = 0;

        for (int i = 0; i < s.length(); i++) {
            re = (char) (re ^ s.charAt(i));
        }

        for (int i = 0; i < t.length(); i++) {
            re = (char) (re ^ t.charAt(i));
        }

        return re;
    }

    public static void main(String[] args) {
        System.out.println(findTheDifference("", "a"));
    }

}
